import mongoose, { Schema, Document, ObjectId } from "mongoose";

export interface IChapterTest extends Document {
  _id: ObjectId;
  bookId: ObjectId;
  chapterId: string;
  title: string;
  description?: string;
  keywords: Array<{
    keyword: string;
    frequency: number;
    relevance: number;
  }>;
  duration: number; // in minutes
  totalQuestions: number;
  passingScore: number;
  questions: ObjectId[];
  relatedTopics: string[];
  prerequisites: string[];
  autoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const chapterTestSchema = new Schema<IChapterTest>(
  {
    bookId: {
      type: Schema.Types.ObjectId,
      ref: "Book",
      required: true,
      index: true,
    },
    chapterId: { type: String, required: true, index: true },
    title: { type: String, required: true },
    description: String,
    keywords: [
      {
        keyword: String,
        frequency: Number,
        relevance: Number,
      },
    ],
    duration: { type: Number, required: true },
    totalQuestions: { type: Number, required: true },
    passingScore: { type: Number, default: 60 },
    questions: [{ type: Schema.Types.ObjectId, ref: "Question" }],
    relatedTopics: [String],
    prerequisites: [String],
    autoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true },
);

chapterTestSchema.index({ bookId: 1, chapterId: 1 });

export const ChapterTest = mongoose.model<IChapterTest>(
  "ChapterTest",
  chapterTestSchema,
);
